### ISSUE TITLE
Breite des Trafficwidgets wird nicht richtig propagiert

### ISSUE THREAD

**Issue by janLo** [agdsn/newfront-draft2#3]
Das hat zur Folge, das dies beim Skalieren in bestimmten Grüßen "abgeschnitten" wird. Siehe Screenshot:

![agdsn](https://cloud.githubusercontent.com/assets/96146/4810616/956c4b5a-5eb4-11e4-8a50-a86f504d01bf.png)

**Comment by mueslo** [comment]
Den von @janLo beschriebenen Bug behebt das aber nicht.

**Comment by gwTumm** [comment]
Es behebt den Rendering-Glitch aus dem letzten Screenshot; Das Traffic-Widget reagiert aber auch weiter nicht auf Resize (vorletzter Screenshot).
